<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Avatar</title>
    <link rel="stylesheet" href="css/style.css">
    <script src="js/index.js" type="module" async></script>
</head>

<body>
    <header>
        <h1>Avatar Factory</h1>
    </header>
    <main>
        <div class="svg-container"></div>

        <!-- FORMULAIRE DE GENERATION DE L'AVATAR -->
        <button id="previous-avatar">Previous</button>
        <form id="generate-avatar-form" action="index.php" method="get">
            <fieldset>
                <legend>Options de l'avatar</legend>
                <div>
                    <label for="number-of-colors">Nombre de couleurs</label>
                    <select id="number-of-colors" name="number-of-colors">
                        <?php for ($n = 2; $n < 5; $n++) : ?>
                            <option value="<?= $n ?>"><?= $n ?></option>
                        <?php endfor; ?>
                    </select>
                </div>
                <div>
                    <label for="size">Taille</label>
                    <select id="size" name="size">
                        <?php for ($n = 3; $n < 8; $n++) : ?>
                            <option value="<?= $n ?>"><?= $n ?></option>
                        <?php endfor; ?>
                    </select>
                </div>
            </fieldset>
            <input type="submit" value="Générer">
        </form>
        <button id="next-avatar">Next</button>

        <!-- FORMULAIRE D'ENREGISTREMENT DE L'AVATAR -->
        <form id="save-avatar-form" action="save.php" method="post">
            <input type="hidden" name="svg">
            <input type="submit" value="Enregistrer">
        </form>

        <button id="copy-svg-source">Copier le SVG</button>
        <a href="#" id="download-png">Télécharger en PNG</a>
    </main>
</body>

</html>